### ISSUE TITLE
Failed to load the TLS Client asset: Unable to find asset tls-client-windows-64-vNone.dll for version None.

### ISSUE THREAD

**Issue by nazavod777** [rawandahmad698/noble-tls#4]
Compiling by pyarmor with command
pyarmor-7 pack --clean -e "--onefile --icon=logo.ico --add-binary C:/Users/unknown/AppData/Local/Programs/Python/Python310/Lib/site-packages/noble_tls/dependencies/tls-client-windows-64-v1.7.2.dll;noble_tls/dependencies" main.py

but when starting compiled exe have error:
Downloaded asset None for version None.
>> Failed to load the TLS Client asset: Unable to find asset tls-client-windows-64-vNone.dll for version None.
Traceback (most recent call last):
  File "<dist\obf\main.py>", line 3, in <module>
  File "<frozen main>", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "core\__init__.py", line 1, in <module>
    from .accounts_reger import create_account
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "core\accounts_reger.py", line 8, in <module>
    from noble_tls import Session
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "noble_tls\__init__.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "noble_tls\sessions.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "noble_tls\c\cffi.py", line 84, in <module>
AttributeError: 'NoneType' object has no attribute 'request'
[8580] Failed to execute script 'main' due to unhandled exception!

**Comment by nazavod777** [comment]
if change dll name in folder from tls-client-windows-64-v1.7.2.dll to tls-client-windows-64-vNone.dll - works, but need to fix anyway

**Comment by 1makarov** [comment]
Привет

**Comment by werfwes** [comment]
> Привет

привет

**Comment by godlikemelancholy** [comment]
Привет

**Comment by rawandahmad698** [comment]
> if change dll name in folder from tls-client-windows-64-v1.7.2.dll to tls-client-windows-64-vNone.dll - works, but need to fix anyway

What do you mean?

**Comment by nazavod777** [comment]
> > if change dll name in folder from tls-client-windows-64-v1.7.2.dll to tls-client-windows-64-vNone.dll - works, but need to fix anyway
> 
> What do you mean?

![image](https://github.com/rawandahmad698/noble-tls/assets/91217742/668195ce-4de1-4788-90a8-08e7047c2d20)
now its look like this, i need to copy tls-client-windows-64-v1.7.2.dll file and rename version 1.7.2 to None cuz when compiling and running script i get Downloaded asset None for version None., Not 1.7.2, its None Version

**Comment by rawandahmad698** [comment]
That's weird. Can you update to 104 and lmk if it works?
